version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: congo_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME:-congo_knowledge_db}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7
    container_name: congo_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: app_kongo_sirius
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app

volumes:
  db_data:
